In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
root_dir = "/content/drive/MyDrive/Felix/Sample Data files"

In [3]:
os.listdir(root_dir)

['DE1_0_2008_to_2010_Inpatient_Claims_Sample_20.csv',
 'DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv',
 'DE1_0_2008_to_2010_Carrier_Claims_Sample_20B.csv',
 'DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.csv',
 'DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20.csv',
 'DE1_0_2008_Beneficiary_Summary_File_Sample_20.csv',
 'DE1_0_2009_Beneficiary_Summary_File_Sample_20.csv',
 'DE1_0_2010_Beneficiary_Summary_File_Sample_20.csv',
 '155409_DE1_0_2008_Beneficiary_Summary_File_Sample_20',
 'DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20',
 'Definitions',
 '2018_I9gem.txt',
 'ICD-10_GEM_fact_sheet.pdf',
 'icd9toicd10cmgem.csv']

In [4]:
DE1_0_2008_to_2010_Carrier_Claims_Sample_20A = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv"))
DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.head()

<ipython-input-4-1f1e10005f3c>:1: DtypeWarning: Columns (9,10,11,46,47,48,49,50,135,136,137,138,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  DE1_0_2008_to_2010_Carrier_Claims_Sample_20A = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv"))

,DESYNPUF_ID,CLM_ID,CLM_FROM_DT,CLM_THRU_DT,ICD9_DGNS_CD_1,ICD9_DGNS_CD_2,ICD9_DGNS_CD_3,ICD9_DGNS_CD_4,ICD9_DGNS_CD_5,ICD9_DGNS_CD_6,...,LINE_ICD9_DGNS_CD_4,LINE_ICD9_DGNS_CD_5,LINE_ICD9_DGNS_CD_6,LINE_ICD9_DGNS_CD_7,LINE_ICD9_DGNS_CD_8,LINE_ICD9_DGNS_CD_9,LINE_ICD9_DGNS_CD_10,LINE_ICD9_DGNS_CD_11,LINE_ICD9_DGNS_CD_12,LINE_ICD9_DGNS_CD_13
0,00001C24EE7B06AC,30293373261498,20080114,20080114,4660,78609,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00001C24EE7B06AC,30183375444975,20080212,20080212,46401,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00001C24EE7B06AC,30923373369715,20080224,20080224,34510,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00001C24EE7B06AC,30443377080642,20080305,20080305,4660,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00001C24EE7B06AC,30353376349565,20080311,20080311,4011,78039,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.head()

,DESYNPUF_ID,CLM_ID,CLM_FROM_DT,CLM_THRU_DT,ICD9_DGNS_CD_1,ICD9_DGNS_CD_2,ICD9_DGNS_CD_3,ICD9_DGNS_CD_4,ICD9_DGNS_CD_5,ICD9_DGNS_CD_6,ICD9_DGNS_CD_7,ICD9_DGNS_CD_8,PRF_PHYSN_NPI_1,PRF_PHYSN_NPI_2,PRF_PHYSN_NPI_3,PRF_PHYSN_NPI_4,PRF_PHYSN_NPI_5,PRF_PHYSN_NPI_6,PRF_PHYSN_NPI_7,PRF_PHYSN_NPI_8,PRF_PHYSN_NPI_9,PRF_PHYSN_NPI_10,PRF_PHYSN_NPI_11,PRF_PHYSN_NPI_12,PRF_PHYSN_NPI_13,TAX_NUM_1,TAX_NUM_2,TAX_NUM_3,TAX_NUM_4,TAX_NUM_5,TAX_NUM_6,TAX_NUM_7,TAX_NUM_8,TAX_NUM_9,TAX_NUM_10,TAX_NUM_11,TAX_NUM_12,TAX_NUM_13,HCPCS_CD_1,HCPCS_CD_2,HCPCS_CD_3,HCPCS_CD_4,HCPCS_CD_5,HCPCS_CD_6,HCPCS_CD_7,HCPCS_CD_8,HCPCS_CD_9,HCPCS_CD_10,HCPCS_CD_11,HCPCS_CD_12,HCPCS_CD_13,LINE_NCH_PMT_AMT_1,LINE_NCH_PMT_AMT_2,LINE_NCH_PMT_AMT_3,LINE_NCH_PMT_AMT_4,LINE_NCH_PMT_AMT_5,LINE_NCH_PMT_AMT_6,LINE_NCH_PMT_AMT_7,LINE_NCH_PMT_AMT_8,LINE_NCH_PMT_AMT_9,LINE_NCH_PMT_AMT_10,LINE_NCH_PMT_AMT_11,LINE_NCH_PMT_AMT_12,LINE_NCH_PMT_AMT_13,LINE_BENE_PTB_DDCTBL_AMT_1,LINE_BENE_PTB_DDCTBL_AMT_2,LINE_BENE_PTB_DDCTBL_AMT_3,LINE_BENE_PTB_DDCTBL_AMT_4,LINE_BENE_PTB_DDCTBL_AMT_5,LINE_BENE_PTB_DDCTBL_AMT_6,LINE_BENE_PTB_DDCTBL_AMT_7,LINE_BENE_PTB_DDCTBL_AMT_8,LINE_BENE_PTB_DDCTBL_AMT_9,LINE_BENE_PTB_DDCTBL_AMT_10,LINE_BENE_PTB_DDCTBL_AMT_11,LINE_BENE_PTB_DDCTBL_AMT_12,LINE_BENE_PTB_DDCTBL_AMT_13,LINE_BENE_PRMRY_PYR_PD_AMT_1,LINE_BENE_PRMRY_PYR_PD_AMT_2,LINE_BENE_PRMRY_PYR_PD_AMT_3,LINE_BENE_PRMRY_PYR_PD_AMT_4,LINE_BENE_PRMRY_PYR_PD_AMT_5,LINE_BENE_PRMRY_PYR_PD_AMT_6,LINE_BENE_PRMRY_PYR_PD_AMT_7,LINE_BENE_PRMRY_PYR_PD_AMT_8,LINE_BENE_PRMRY_PYR_PD_AMT_9,LINE_BENE_PRMRY_PYR_PD_AMT_10,LINE_BENE_PRMRY_PYR_PD_AMT_11,LINE_BENE_PRMRY_PYR_PD_AMT_12,LINE_BENE_PRMRY_PYR_PD_AMT_13,LINE_COINSRNC_AMT_1,LINE_COINSRNC_AMT_2,LINE_COINSRNC_AMT_3,LINE_COINSRNC_AMT_4,LINE_COINSRNC_AMT_5,LINE_COINSRNC_AMT_6,LINE_COINSRNC_AMT_7,LINE_COINSRNC_AMT_8,LINE_COINSRNC_AMT_9,LINE_COINSRNC_AMT_10,LINE_COINSRNC_AMT_11,LINE_COINSRNC_AMT_12,LINE_COINSRNC_AMT_13,LINE_ALOWD_CHRG_AMT_1,LINE_ALOWD_CHRG_AMT_2,LINE_ALOWD_CHRG_AMT_3,LINE_ALOWD_CHRG_AMT_4,LINE_ALOWD_CHRG_AMT_5,LINE_ALOWD_CHRG_AMT_6,LINE_ALOWD_CHRG_AMT_7,LINE_ALOWD_CHRG_AMT_8,LINE_ALOWD_CHRG_AMT_9,LINE_ALOWD_CHRG_AMT_10,LINE_ALOWD_CHRG_AMT_11,LINE_ALOWD_CHRG_AMT_12,LINE_ALOWD_CHRG_AMT_13,LINE_PRCSG_IND_CD_1,LINE_PRCSG_IND_CD_2,LINE_PRCSG_IND_CD_3,LINE_PRCSG_IND_CD_4,LINE_PRCSG_IND_CD_5,LINE_PRCSG_IND_CD_6,LINE_PRCSG_IND_CD_7,LINE_PRCSG_IND_CD_8,LINE_PRCSG_IND_CD_9,LINE_PRCSG_IND_CD_10,LINE_PRCSG_IND_CD_11,LINE_PRCSG_IND_CD_12,LINE_PRCSG_IND_CD_13,LINE_ICD9_DGNS_CD_1,LINE_ICD9_DGNS_CD_2,LINE_ICD9_DGNS_CD_3,LINE_ICD9_DGNS_CD_4,LINE_ICD9_DGNS_CD_5,LINE_ICD9_DGNS_CD_6,LINE_ICD9_DGNS_CD_7,LINE_ICD9_DGNS_CD_8,LINE_ICD9_DGNS_CD_9,LINE_ICD9_DGNS_CD_10,LINE_ICD9_DGNS_CD_11,LINE_ICD9_DGNS_CD_12,LINE_ICD9_DGNS_CD_13
0,00001C24EE7B06AC,30293373261498,20080114,20080114,4660,78609,NaN,NaN,NaN,NaN,NaN,NaN,4.458732e+09,4.458732e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29580623,29580623.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,11644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4660,6278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00001C24EE7B06AC,30183375444975,20080212,20080212,46401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.740507e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73518156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00001C24EE7B06AC,30923373369715,20080224,20080224,34510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.625471e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229220908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00001C24EE7B06AC,30443377080642,20080305,20080305,4660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.324555e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,565942996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00001C24EE7B06AC,30353376349565,20080311,20080311,4011,78039,NaN,NaN,NaN,NaN,NaN,NaN,3.833716e+08,3.833716e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309874405,309874405.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99213,82270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4011,4011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
DE1_0_2008_Beneficiary_Summary_File_Sample_20 = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_Beneficiary_Summary_File_Sample_20.csv"))
DE1_0_2008_Beneficiary_Summary_File_Sample_20.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,BENE_HMO_CVRAGE_TOT_MONS,PLAN_CVRG_MOS_NUM,SP_ALZHDMTA,SP_CHF,SP_CHRNKIDN,SP_CNCR,SP_COPD,SP_DEPRESSN,SP_DIABETES,SP_ISCHMCHT,SP_OSTEOPRS,SP_RA_OA,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,000002F7E0A96C32,19190701,NaN,2,2,0,5,400,4,0,0,0,2,2,2,2,2,2,2,2,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,00001C24EE7B06AC,19360501,NaN,1,1,0,11,530,12,0,0,11,2,2,2,2,2,2,2,2,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0,720.0,370.0,0.0
2,000072CF62193213,19310401,NaN,2,1,0,34,120,12,12,0,12,2,1,2,2,2,2,2,2,1,2,2,0.0,0.0,0.0,850.0,150.0,0.0,0.0,0.0,0.0
3,0000DCD33779ED8A,19420501,NaN,2,2,0,11,190,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0,10.0,20.0,0.0
4,0000F1EB530967F3,19350401,NaN,2,1,0,23,720,12,12,0,0,1,1,1,2,1,1,1,1,1,1,1,4000.0,1024.0,0.0,20.0,0.0,0.0,4840.0,1260.0,0.0

In [8]:
DE1_0_2008_to_2010_Outpatient_Claims_Sample_20 = DE1_0_2008_Beneficiary_Summary_File_Sample_20 = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.csv"))
DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.head()

<ipython-input-8-c173eca60b5b>:1: DtypeWarning: Columns (21,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  DE1_0_2008_to_2010_Outpatient_Claims_Sample_20 = DE1_0_2008_Beneficiary_Summary_File_Sample_20 = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.csv"))

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,OT_PHYSN_NPI,NCH_BENE_BLOOD_DDCTBL_LBLTY_AM,ICD9_DGNS_CD_1,ICD9_DGNS_CD_2,ICD9_DGNS_CD_3,ICD9_DGNS_CD_4,ICD9_DGNS_CD_5,ICD9_DGNS_CD_6,ICD9_DGNS_CD_7,ICD9_DGNS_CD_8,ICD9_DGNS_CD_9,ICD9_DGNS_CD_10,ICD9_PRCDR_CD_1,ICD9_PRCDR_CD_2,ICD9_PRCDR_CD_3,ICD9_PRCDR_CD_4,ICD9_PRCDR_CD_5,ICD9_PRCDR_CD_6,NCH_BENE_PTB_DDCTBL_AMT,NCH_BENE_PTB_COINSRNC_AMT,ADMTNG_ICD9_DGNS_CD,HCPCS_CD_1,HCPCS_CD_2,HCPCS_CD_3,HCPCS_CD_4,HCPCS_CD_5,HCPCS_CD_6,HCPCS_CD_7,HCPCS_CD_8,HCPCS_CD_9,HCPCS_CD_10,HCPCS_CD_11,HCPCS_CD_12,HCPCS_CD_13,HCPCS_CD_14,HCPCS_CD_15,HCPCS_CD_16,HCPCS_CD_17,HCPCS_CD_18,HCPCS_CD_19,HCPCS_CD_20,HCPCS_CD_21,HCPCS_CD_22,HCPCS_CD_23,HCPCS_CD_24,HCPCS_CD_25,HCPCS_CD_26,HCPCS_CD_27,HCPCS_CD_28,HCPCS_CD_29,HCPCS_CD_30,HCPCS_CD_31,HCPCS_CD_32,HCPCS_CD_33,HCPCS_CD_34,HCPCS_CD_35,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00001C24EE7B06AC,684562269783396,1,20090404.0,20090404.0,1100SK,200.0,0.0,1.298827e+09,NaN,NaN,0.0,74560,V5861,42731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.0,NaN,93303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00001C24EE7B06AC,684012269893042,1,20100310.0,20100310.0,1100SK,500.0,0.0,1.298827e+09,NaN,NaN,0.0,7879,V4589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,74000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000072CF62193213,684012269540703,1,20080130.0,20080130.0,1000AH,50.0,0.0,8.929521e+09,NaN,8.523329e+09,0.0,4019,73300,79431,V5869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,80053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,000072CF62193213,684472269696971,1,20080301.0,20080301.0,1000AH,70.0,0.0,8.382688e+09,NaN,NaN,0.0,4019,71699,V7644,78605,7226,V1582,43882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,20.0,NaN,36415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,000072CF62193213,684122269778934,1,20080322.0,20080322.0,3400HK,40.0,0.0,4.404237e+09,NaN,NaN,0.0,1736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,1733,88305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
DE1_0_2008_to_2010_Inpatient_Claims_Sample_20  = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Inpatient_Claims_Sample_20.csv"))
DE1_0_2008_to_2010_Inpatient_Claims_Sample_20.head()

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,OT_PHYSN_NPI,CLM_ADMSN_DT,ADMTNG_ICD9_DGNS_CD,CLM_PASS_THRU_PER_DIEM_AMT,NCH_BENE_IP_DDCTBL_AMT,NCH_BENE_PTA_COINSRNC_LBLTY_AM,NCH_BENE_BLOOD_DDCTBL_LBLTY_AM,CLM_UTLZTN_DAY_CNT,NCH_BENE_DSCHRG_DT,CLM_DRG_CD,ICD9_DGNS_CD_1,ICD9_DGNS_CD_2,ICD9_DGNS_CD_3,ICD9_DGNS_CD_4,ICD9_DGNS_CD_5,ICD9_DGNS_CD_6,ICD9_DGNS_CD_7,ICD9_DGNS_CD_8,ICD9_DGNS_CD_9,ICD9_DGNS_CD_10,ICD9_PRCDR_CD_1,ICD9_PRCDR_CD_2,ICD9_PRCDR_CD_3,ICD9_PRCDR_CD_4,ICD9_PRCDR_CD_5,ICD9_PRCDR_CD_6,HCPCS_CD_1,HCPCS_CD_2,HCPCS_CD_3,HCPCS_CD_4,HCPCS_CD_5,HCPCS_CD_6,HCPCS_CD_7,HCPCS_CD_8,HCPCS_CD_9,HCPCS_CD_10,HCPCS_CD_11,HCPCS_CD_12,HCPCS_CD_13,HCPCS_CD_14,HCPCS_CD_15,HCPCS_CD_16,HCPCS_CD_17,HCPCS_CD_18,HCPCS_CD_19,HCPCS_CD_20,HCPCS_CD_21,HCPCS_CD_22,HCPCS_CD_23,HCPCS_CD_24,HCPCS_CD_25,HCPCS_CD_26,HCPCS_CD_27,HCPCS_CD_28,HCPCS_CD_29,HCPCS_CD_30,HCPCS_CD_31,HCPCS_CD_32,HCPCS_CD_33,HCPCS_CD_34,HCPCS_CD_35,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,0000F1EB530967F3,338091165532547,1,20080327.0,20080403.0,2302KU,4000.0,0.0,9.833008e+09,1.723548e+09,NaN,20080327,431,0.0,1024.0,0.0,0.0,7.0,20080403,208,5070,E8769,V5869,38600,2724,496,V5489,9351,56400,NaN,4311.0,34590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00036DA073115F08,338691165529304,1,20080829.0,20080902.0,3600CS,7000.0,0.0,5.333646e+09,5.333646e+09,NaN,20080829,5933,0.0,1024.0,0.0,0.0,4.0,20080902,662,5920,7856,V1301,V5869,NaN,NaN,NaN,NaN,NaN,NaN,5551.0,29680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00036DA073115F08,338881165476888,1,20080906.0,20080908.0,3600CS,6000.0,0.0,5.333646e+09,NaN,NaN,20080906,5939,0.0,1024.0,0.0,0.0,2.0,20080908,693,1981,5990,56409,60000,2724,311,4254,V1005,4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0003D0FBC87B8600,338161165483669,1,20091029.0,20091102.0,0300QJ,8000.0,0.0,9.059627e+09,7.308255e+09,NaN,20091029,78605,0.0,1068.0,0.0,0.0,4.0,20091102,186,49121,2662,2761,78791,4019,7140,2859,34590,36250,NaN,481.0,29281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,000994C65A0D1143,338781165536222,1,20080429.0,20080509.0,1501ZA,7000.0,0.0,7.234907e+09,5.401024e+09,NaN,20080429,27651,0.0,1024.0,0.0,0.0,10.0,20080509,203,5119,41400,V1251,72700,42731,79902,53081,412,3559,NaN,3326.0,2766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20  = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20","DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20.csv"))
DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20.head()

<ipython-input-10-49bd7ef3cf93>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20  = pd.read_csv(os.path.join(root_dir, "DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20","DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20.csv"))

,DESYNPUF_ID,PDE_ID,SRVC_DT,PROD_SRVC_ID,QTY_DSPNSD_NUM,DAYS_SUPLY_NUM,PTNT_PAY_AMT,TOT_RX_CST_AMT
0,00001C24EE7B06AC,376274477280599,20080123,67544027594,240.0,30,10.0,10.0
1,00001C24EE7B06AC,376444478082254,20080203,51129391601,360.0,10,0.0,0.0
2,00001C24EE7B06AC,376404478575218,20080301,00179143501,90.0,30,0.0,20.0
3,00001C24EE7B06AC,376734479470427,20080312,66105012206,30.0,10,0.0,10.0
4,00001C24EE7B06AC,376604482751046,20080505,10864001102,30.0,20,0.0,20.0

### DATA PREPARATION

In [4]:
os.listdir(root_dir)

['DE1_0_2008_to_2010_Inpatient_Claims_Sample_20.csv',
 'DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv',
 'DE1_0_2008_to_2010_Carrier_Claims_Sample_20B.csv',
 'DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.csv',
 'DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20.csv',
 'DE1_0_2008_Beneficiary_Summary_File_Sample_20.csv',
 'DE1_0_2009_Beneficiary_Summary_File_Sample_20.csv',
 'DE1_0_2010_Beneficiary_Summary_File_Sample_20.csv',
 '155409_DE1_0_2008_Beneficiary_Summary_File_Sample_20',
 'DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_20',
 'Definitions',
 '2018_I9gem.txt',
 'ICD-10_GEM_fact_sheet.pdf',
 'icd9toicd10cmgem.csv']

#### PATIENT DEMOGRAPHICS

In [4]:
import pandas as pd
from datetime import datetime
import numpy as np


dfs = []
for year in ['2008', '2009', '2010']:
    df = pd.read_csv(os.path.join(root_dir,f'DE1_0_{year}_Beneficiary_Summary_File_Sample_20.csv'))
    df['Year'] = year
    dfs.append(df)


ben_df = pd.concat(dfs, ignore_index=True)


ben_sets = {year: set(df['DESYNPUF_ID']) for year, df in ben_df.groupby('Year')}


ben_df['NewEnrollee'] = False
for year, ben_set in ben_sets.items():
    if year == '2008': # no previous year to check
        continue
    prev_year = str(int(year) - 1)
    ben_df.loc[(ben_df['Year'] == year) & (~ben_df['DESYNPUF_ID'].isin(ben_sets[prev_year])), 'NewEnrollee'] = True


ben_df.rename(columns={'DESYNPUF_ID':'MBI',
                       'BENE_SEX_IDENT_CD':'SEX',
                       'BENE_BIRTH_DT':'DOB'}, inplace=True)


ben_df['LTIMCAID'] = np.where(ben_df['MEDREIMB_IP'] > 0, 1, 0)


ben_df['NEMCAID'] = np.where(ben_df['NewEnrollee'] & (ben_df['MEDREIMB_IP'] > 0), 1, 0)


ben_df['DOB'] = pd.to_datetime(ben_df['DOB'], format='%Y%m%d')
ben_df['AGE'] = ben_df['Year'].astype(int) - ben_df['DOB'].dt.year


conditions = [
    (ben_df['AGE'] >= 65), # old age
    (ben_df['AGE'] < 65) & (ben_df['BENE_ESRD_IND'] == 0), # disability
    (ben_df['BENE_ESRD_IND'] == 1), # ESRD
]
choices = ['0', '1', '2'] # corresponding OREC codes

ben_df['OREC'] = np.select(conditions, choices, default='0') # default to old age if none of conditions met


ben_df = ben_df[['MBI', 'SEX', 'DOB', 'LTIMCAID', 'NEMCAID', 'OREC']]


ben_df.to_csv('person_file.csv', index=False)
ben_df.head()

                MBI  SEX        DOB  LTIMCAID  NEMCAID OREC
0  000002F7E0A96C32    2 1919-07-01         0        0    0
1  00001C24EE7B06AC    1 1936-05-01         0        0    0
2  000072CF62193213    2 1931-04-01         0        0    0
3  0000DCD33779ED8A    2 1942-05-01         0        0    0
4  0000F1EB530967F3    2 1935-04-01         1        0    0

In [5]:
ben_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343827 entries, 0 to 343826
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   MBI       343827 non-null  object
 1   SEX       343827 non-null  int64
 2   DOB       343827 non-null  datetime64[ns]
 3   LTIMCAID  343827 non-null  int64
 4   NEMCAID   343827 non-null  int64
 5   OREC      343827 non-null  object
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 15.7+ MB

#### DISEASE

In [ ]:
import pandas as pd


df_carrier_a = pd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv'))


df_carrier_a_claim_level = df_carrier_a.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], 
                                             value_vars=[f'ICD9_DGNS_CD_{i}' for i in range(1, 9)], 
                                             value_name='DIAG')


df_carrier_a_line_level = df_carrier_a.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], 
                                            value_vars=[f'LINE_ICD9_DGNS_CD_{i}' for i in range(1, 14)], 
                                            value_name='DIAG')


df_carrier_a = pd.concat([df_carrier_a_claim_level, df_carrier_a_line_level])


df_carrier_b = pd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Carrier_Claims_Sample_20B.csv'))


df_carrier_b_claim_level = df_carrier_b.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], 
                                             value_vars=[f'ICD9_DGNS_CD_{i}' for i in range(1, 9)], 
                                             value_name='DIAG')


df_carrier_b_line_level = df_carrier_b.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], 
                                            value_vars=[f'LINE_ICD9_DGNS_CD_{i}' for i in range(1, 14)], 
                                            value_name='DIAG')


df_carrier_b = pd.concat([df_carrier_b_claim_level, df_carrier_b_line_level])


df_carrier = pd.concat([df_carrier_a, df_carrier_b])


df_carrier = df_carrier.dropna(subset=['DIAG'])


df_carrier.to_csv('DIAG.csv', index=False)
df_carrier.head()

<ipython-input-6-e8a7ccf09739>:4: DtypeWarning: Columns (9,10,11,46,47,48,49,50,135,136,137,138,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df_carrier_a = pd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv'))

In [14]:
import dask.dataframe as dd


ddf_carrier_a = dd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Carrier_Claims_Sample_20A.csv'), dtype=str)
ddf_carrier_b = dd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Carrier_Claims_Sample_20B.csv'), dtype=str)


def reshape_ddf(ddf):
    ddf_claim_level = ddf.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'],
                               value_vars=[f'ICD9_DGNS_CD_{i}' for i in range(1, 9)],
                               value_name='DIAG')
    ddf_line_level = ddf.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'],
                              value_vars=[f'LINE_ICD9_DGNS_CD_{i}' for i in range(1, 14)],
                              value_name='DIAG')
    return dd.concat([ddf_claim_level, ddf_line_level])


ddf_carrier_a = reshape_ddf(ddf_carrier_a)
ddf_carrier_b = reshape_ddf(ddf_carrier_b)


ddf_carrier = dd.concat([ddf_carrier_a, ddf_carrier_b])


ddf_carrier = ddf_carrier.dropna(subset=['DIAG'])

ddf_inpatient = dd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Inpatient_Claims_Sample_20.csv'), dtype=str, assume_missing=True)


ddf_outpatient = dd.read_csv(os.path.join(root_dir,'DE1_0_2008_to_2010_Outpatient_Claims_Sample_20.csv'), dtype=str, assume_missing=True)

ddf_inpatient = ddf_inpatient.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], value_vars=[f'ICD9_DGNS_CD_{i}' for i in range(1, 9)], value_name='DIAG')
ddf_outpatient = ddf_outpatient.melt(id_vars=['DESYNPUF_ID', 'CLM_FROM_DT'], value_vars=[f'ICD9_DGNS_CD_{i}' for i in range(1, 9)], value_name='DIAG')


ddf_all = dd.concat([ddf_carrier, ddf_inpatient, ddf_outpatient])


ddf_all.head()

        DESYNPUF_ID CLM_FROM_DT        variable   DIAG
0  00001C24EE7B06AC    20080114  ICD9_DGNS_CD_1   4660
1  00001C24EE7B06AC    20080212  ICD9_DGNS_CD_1  46401
2  00001C24EE7B06AC    20080224  ICD9_DGNS_CD_1  34510
3  00001C24EE7B06AC    20080305  ICD9_DGNS_CD_1   4660
4  00001C24EE7B06AC    20080311  ICD9_DGNS_CD_1   4011

In [25]:
import dask
with dask.config.set({
    'dataframe.output.max_rows': 300,   
    'dataframe.output.max_columns': 50  
}):
    display(ddf_all.compute())

              DESYNPUF_ID CLM_FROM_DT        variable   DIAG
0        00001C24EE7B06AC    20080114  ICD9_DGNS_CD_1   4660
1        00001C24EE7B06AC    20080212  ICD9_DGNS_CD_1  46401
2        00001C24EE7B06AC    20080224  ICD9_DGNS_CD_1  34510
3        00001C24EE7B06AC    20080305  ICD9_DGNS_CD_1   4660
4        00001C24EE7B06AC    20080311  ICD9_DGNS_CD_1   4011
...                   ...         ...             ...    ...
3159867  FFFE6F53545F974E    20100109  ICD9_DGNS_CD_8    NaN
3159868  FFFE6F53545F974E    20100223  ICD9_DGNS_CD_8    NaN
3159869  FFFE6F53545F974E    20100312  ICD9_DGNS_CD_8    NaN
3159870  FFFE6F53545F974E    20100805  ICD9_DGNS_CD_8    NaN
3159871  FFFE6F53545F974E    20101013  ICD9_DGNS_CD_8    NaN

[26115166 rows x 4 columns]

In [23]:
ddf_all.head(100)

         DESYNPUF_ID CLM_FROM_DT        variable   DIAG
0   00001C24EE7B06AC    20080114  ICD9_DGNS_CD_1   4660
1   00001C24EE7B06AC    20080212  ICD9_DGNS_CD_1  46401
2   00001C24EE7B06AC    20080224  ICD9_DGNS_CD_1  34510
3   00001C24EE7B06AC    20080305  ICD9_DGNS_CD_1   4660
4   00001C24EE7B06AC    20080311  ICD9_DGNS_CD_1   4011
..               ...         ...             ...    ...
95  0000F1EB530967F3    20081224  ICD9_DGNS_CD_1   5849
96  0000F1EB530967F3    20090203  ICD9_DGNS_CD_1   1537
97  0000F1EB530967F3    20090227  ICD9_DGNS_CD_1  71595
98  0000F1EB530967F3    20090302  ICD9_DGNS_CD_1   4279
99  0000F1EB530967F3    20090310  ICD9_DGNS_CD_1  71534

[100 rows x 4 columns]

In [17]:
ddf_all.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 4 entries, DESYNPUF_ID to DIAG
dtypes: object(4)

In [18]:
ddf_all.shape

(Delayed('int-001258d6-242d-43f3-9139-4dd8234a4df4'), 4)

In [19]:
ddf_all.describe().compute()

             DESYNPUF_ID CLM_FROM_DT        variable      DIAG
unique             99323        1123              21     13520
count           26115166    26026414        26115166  21792726
top     44F61097F45CDCDD    20090228  ICD9_DGNS_CD_1      4019
freq                1517       30251         5603659    648789

In [ ]:
ddf_all.info().compute()

In [20]:
ddf_all.to_csv(os.path.join(root_dir,'DIAG.csv'), index=False, single_file=True)

['/content/drive/MyDrive/Felix/Sample Data files/DIAG.csv']